/**
 * Your Copyright Here
 *
 * Appcelerator Titanium is Copyright (c) 2009-2010 by Appcelerator, Inc.
 * and licensed under the Apache Public License (version 2)
 */
#import "ComLeftlanelabFirebaseModule.h"
#import "TiHost.h"
#import "TiBase.h"
#import "TiUtils.h"

@implementation ComLeftlanelabFirebaseModule

@synthesize url;
@synthesize gInstances;
@synthesize gEventTypes;
@synthesize gListeners;

#pragma mark Internal

// this is generated for your module, please do not change it
-(id)moduleGUID
{
	return @"45ea9836-0715-4f0c-a308-b6f0997431a9";
}

// this is generated for your module, please do not change it
-(NSString*)moduleId
{
	return @"com.leftlanelab.firebase";
}

#pragma mark Lifecycle

-(void)startup
{
	// this method is called when the module is first loaded
	// you *must* call the superclass
	[super startup];

    // Initialize [gEventTypes]
    self.gEventTypes = @[@"child_added", @"child_removed", @"child_changed", @"child_moved", @"value"];

    // Initialize [gInstances]
    self.gInstances = [NSMutableDictionary dictionary];

    // Initialize [gListeners]
    self.gListeners = [NSMutableDictionary dictionary];

    // Enable Automatic Local Persistence
    [Firebase setOption:@"persistence" to:@YES];
}

-(void)shutdown:(id)sender
{
	// this method is called when the module is being unloaded
	// typically this is during shutdown. make sure you don't do too
	// much processing here or the app will be quit forceably
	
	// you *must* call the superclass
	NSLog(@"[INFO] %@ Shutdown", self);
	[super shutdown:sender];
}

#pragma mark Cleanup 

-(void)dealloc
{
	// release any resources that have been retained by the module
	NSLog(@"[INFO] %@ Deallocating", self);
	[super dealloc];
}

#pragma mark Internal Memory Management

-(void)didReceiveMemoryWarning:(NSNotification*)notification
{
	// optionally release any resources that can be dynamically
	// reloaded once memory is available - such as caches
	[super didReceiveMemoryWarning:notification];
	NSLog(@"[INFO] %@ Memory Warning!!!", self);
}

#pragma mark Listener Notifications

/*
-(void)_listenerAdded:(NSString *)type count:(int)count
{
}

-(void)_listenerRemoved:(NSString *)type count:(int)count
{
}
*/

#pragma Public APIs

/**
 * Authenticate access to this Firebase
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (NSString) The Firebase authentication JWT generated by a secure code on a remote server.
 *  - args[2] - (KrollCallback) called with the results of the authentication attempt
 *  - args[3] - (KrollCallback) called if at any time in the future the credentials become invalid
 *
 */
- (void)auth: (id)args
{
    if (! [args count] > 1) {return;}
	
	// Initialize the [arguments]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	NSString *_credential = ([args[1] isKindOfClass:[NSString class]] ? args[1] : nil);
	KrollCallback *_onComplete = ([args count] > 2 && [args[2] isKindOfClass:[KrollCallback class]] ? args[2] : nil);
	KrollCallback *_onCancel = ([args count] > 3 && [args[3] isKindOfClass:[KrollCallback class]] ? args[3] : nil);
	
	// Argument Filter
	if (! _url || ! _credential) {return;}
	
	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] authWithCredential:_credential withCompletionBlock:(! _onComplete ? nil : ^(NSError *error, id data)
	{
		// Execute [onComplete] callback
		[_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc]), (data ? data : [NSNull alloc])] thisObject:nil];

	}) withCancelBlock:(! _onCancel ? nil : ^(NSError *error)
	{
		// Execute [onCancel] callback
		[_onCancel call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];

	})];
}

/**
 * De-Authenticate access to this Firebase
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *  - args[1] - (KrollCallback) called with the results of the authentication attempt
 *
 */
- (void)unauth: (id)args
{
    if (! [args count]) {return;}
	
	// Initialize the [arguments]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_onComplete = ([args count] > 1 && [args[1] isKindOfClass:[KrollCallback class]] ? args[1] : nil);
	
	// Argument Filter
	if (! _url) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] unauthWithCompletionBlock:(! _onComplete ? nil : ^(NSError *error)
	{
		// Execute [onComplete] callback
		[_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];
	})];
}

/**
 * Set [instance]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (id) values to be updated
 *  - args[2] - (KrollCallback) callback
 *
 */
- (void)set: (id)args
{
    if (! [args count] > 1) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_onComplete = ([args count] > 2 && [args[2] isKindOfClass:[KrollCallback class]] ? args[2] : nil);

	// Argument Filter
	if (! _url) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] setValue:args[1] withCompletionBlock:(! _onComplete ? nil : ^(NSError *error, Firebase *ref)
	{
		// Execute [onComplete] callback
		[_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];
	})];
}

/**
 * Update [instance]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (id) values to be updated
 *  - args[2] - (KrollCallback) callback
 *
 */
- (void)update: (id)args
{
    if (! [args count] > 1) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_onComplete = ([args count] > 2 && [args[2] isKindOfClass:[KrollCallback class]] ? args[2] : nil);

	// Argument Filter
	if (! _url) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] updateChildValues:args[1] withCompletionBlock:(! _onComplete ? nil : ^(NSError *error, Firebase *ref)
	{
		// Execute [onComplete] callback
		[_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];
	})];
}

/**
 * Remove data from [instance]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *  - args[1] - (KrollCallback) callback
 *
 */
- (void)remove: (id)args
{
    if (! [args count]) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_onComplete = ([args count] > 1 && [args[1] isKindOfClass:[KrollCallback class]] ? args[1] : nil);

	// Argument Filter
	if (! _url) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] removeValueWithCompletionBlock:(! _onComplete ? nil : ^(NSError *error, Firebase *ref)
	{
		// Execute [onComplete] callback
		[_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];
	})];
}

/**
 * Generate new [child] w/AutoID
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *
 *	Returns: (NSString) new [child].[name]
 */
- (NSString*)push: (id)args
{
	if (! [args count]) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);

	// Argument Filter
	if (! _url) {return;}

	// Create the new [child] and return [name]
	return [[[Firebase alloc] initWithUrl:_url] childByAutoId].name;
}

/**
 * Set [instance] with [priority]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (id) values to be set
 *	- args[2] - (id) priority to be set
 *  - args[3] - (KrollCallback) callback
 *
 */
- (void)setWithPriority: (id)args
{
    if (! [args count] > 2) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_onComplete = ([args count] > 3 && [args[3] isKindOfClass:[KrollCallback class]] ? args[3] : nil);

	// Argument Filter
	if (! _url) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] setValue:args[1] andPriority:args[2] withCompletionBlock:(! _onComplete ? nil : ^(NSError *error, Firebase *ref)
	{
		// Execute [onComplete] callback
		[_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];
	})];
}

/**
 * Set [priority] of [instance]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (id) priority to be set
 *  - args[2] - (KrollCallback) callback
 *
 */
- (void)setPriority: (id)args
{
    if (! [args count] > 1) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_onComplete = ([args count] > 2 && [args[2] isKindOfClass:[KrollCallback class]] ? args[2] : nil);

	// Argument Filter
	if (! _url) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] setPriority:args[1] withCompletionBlock:(! _onComplete ? nil : ^(NSError *error, Firebase *ref)
	{
		// Execute [onComplete] callback
		NSString *_test = [_onComplete call:@[(error ? [error localizedDescription] : [NSNull alloc])] thisObject:nil];
		NSLog(@"[INFO] Return from onComplete: %@", _test);
	})];
}

/**
 * Atomically modify the data of [instance]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *  - args[1] - (KrollCallback) updateFunction callback
 *	- args[2] - (NSNumber) applyLocally (default: YES)
 *  - args[3] - (KrollCallback) onComplete callback
 *
 */
- (void)transaction: (id)args
{
    if (! [args count] > 2) {return;}

	// Initialize the [args]
	NSString *_url = ([args[0] isKindOfClass:[NSString class]] ? args[0] : nil);
	KrollCallback *_updateFunction = ([args[1] isKindOfClass:[KrollCallback class]] ? args[1] : nil);
	BOOL *_applyLocally = ([args[2] isKindOfClass:[NSNumber class]] ? ([args[2] isEqualToNumber:[NSNumber numberWithBool:YES]]) : YES);
	KrollCallback *_onComplete = ([args count] > 3 && [args[3] isKindOfClass:[KrollCallback class]] ? args[3] : nil);

	// Argument Filter
	if (! _url || ! _updateFunction) {return;}

	// Kick the Firebase
	[[[Firebase alloc] initWithUrl:_url] runTransactionBlock:^FTransactionResult *(FMutableData *currentData)
	{
		// Execute [updateFunction] callback
		NSLog(@"[INFO] Return from updateFunction: %@", currentData.value);

//		currentData.value = [_updateFunction call:@[currentData.value] thisObject:nil];
		//FTransactionResult *_result = [_updateFunction call:@[currentData] thisObject:nil];

		return [FTransactionResult successWithValue:currentData];
	}

	andCompletionBlock:^(NSError *error, BOOL committed, FDataSnapshot *snapshot)
	{

		
	}

	withLocalEvents:_applyLocally];
}

/**
 * Create a Firebase [listener] and return a [handle]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (NSString) Event Type to listen for
 *  - args[2] - (KrollCallback) callback
 *  - args[3] - (id) context for callback
 *
 */
-(id)on: (id)args
{
	// Initialize the [arguments]
	NSString *_url = ([args count] && ! [args[0] isKindOfClass:[NSNull class]] ? args[0] : nil);
	NSString *_type = ([args count] > 1 && ! [args[1] isKindOfClass:[NSNull class]] ? args[1] : nil);
	KrollCallback *_callback = ([args count] > 2 && ! [args[2] isKindOfClass:[NSNull class]] ? args[2] : nil);
	id _context = ([args count] > 3 && ! [args[3] isKindOfClass:[NSNull class]] ? args[3] : nil);

	NSLog(@"[INFO] Adding Listener: %@ (%@)", _type, _url);

	// Argument Filter
	if (! _url || ! _type || ! _callback) {return NO;}

	// Search for [type] in [gEventTypes]
	NSUInteger _search = [self.gEventTypes indexOfObject:_type];
	if (_search == NSNotFound) {return;}

	// Initialize [event] from [search]
	int* _event = _search;

	// Initialize [gInstances] for [url] (only done once p/[url])
	if (! self.gInstances[_url])
	{
		[self.gInstances setObject:[[Firebase alloc] initWithUrl:_url] forKey:_url];
		[self.gListeners setObject:[NSMutableDictionary dictionary] forKey:_url];
	}

	// Set the [handle] while creating a [listener]
	FirebaseHandle _handle = [self.gInstances[_url] observeEventType:_event withBlock:^(FDataSnapshot *_snapshot)
	{
		// Execute [callback]
		[_callback call:@[[NSMutableDictionary dictionaryWithObject:[self FDataSnapshotSpider:_snapshot] forKey:@"snapshot"]] thisObject:_context];
	}];

	// Initialize the [key] for [handle]
	NSNumber *_key = [NSNumber numberWithInteger:_handle];

	// Save the [handle] in [gListeners].[type]
	[self.gListeners[_url] setObject:_key forKey:_key];

	NSLog(@"[INFO] Returning Handle: (%@)", _key);

	// Return the [key] for future reference
	return _key;
}

/**
 * Remove a Firebase [listener] by [handle]
 *
 *	- args[0] - (NSString) the URL for Firebase Reference
 *	- args[1] - (NSString) Event Type to remove
 *	- args[2] - (NSNumber) Key to [gListeners][type] for [handle]
 *
 */
-(void)off: (id)args
{
	// Initialize the [arguments]
	NSString *_url = ([args count] && ! [args[0] isKindOfClass:[NSNull class]] ? args[0] : nil);
	NSString *_type = ([args count] > 1 && ! [args[1] isKindOfClass:[NSNull class]] ? args[1] : nil);
	NSNumber *_key = ([args count] > 2 && ! [args[2] isKindOfClass:[NSNull class]] ? args[2] : nil);

	NSLog(@"[INFO] Removing Listener: %@ (%@)", _type, _key);

	// Argument Filter
	if (! _url || ! _type || ! _key) {return;}

	// Search for [type] in [gEventTypes]
	NSUInteger _search = [self.gEventTypes indexOfObject:_type];
	if (_search == NSNotFound) {return;}

	// Initialize [event] from [search]
	int* _event = _search;

	// Ensure there is a [gInstance] for this [url]
	if (! self.gInstances[_url]) {

		// Take the opportunity to release [gListeners].[url] if needed
		if (self.gListeners[_url]) {
			[self.gListeners removeObjectForKey:_url];
		}

		return;
	}

	// Ensure there is a [gListener] for this [url] && [key]
	if (! self.gListeners[_url])
	{
		// Take the opportunity to release [gInstances].[url] if needed
		[self.gInstances removeObjectForKey:_url];

		return;
	}

	// Ensure there is a [gListener] for this [key]
	if (! self.gListeners[_url][_key]) {return;}

	// Remove the [listener] by [handle] from [gInstance]
	[self.gInstances[_url] removeObserverWithHandle:[self.gListeners[_url][_key] integerValue]];

	NSLog(@"[INFO] Listener Removed: %@ (%@)", _type, self.gListeners[_url][_key]);

	// Remove the [handle] from [gListeners].[type]
	[self.gListeners[_url] removeObjectForKey:_key];

	// Release [gInstance].[url] if this is the last [gListener]
	if (! [self.gListeners[_url] count])
	{
		NSLog(@"[INFO] Releasing Instance (%@)", _url);

		[self.gListeners removeObjectForKey:_url];
		[self.gInstances removeObjectForKey:_url];

		NSLog(@"[INFO] Released Instance (%@)", _url);
	}
}

#pragma mark Internal Utility Functions

-(id)FDataSnapshotSpider: (FDataSnapshot*)snapshot
{
	// Initialize the [payload]
	NSMutableDictionary *payload = [NSMutableDictionary dictionary];
	
	[payload setObject:(snapshot.name ? snapshot.name : @"root") forKey:@"name"];
	[payload setObject:snapshot.priority forKey:@"priority"];
	[payload setObject:[NSNumber numberWithInteger:snapshot.childrenCount] forKey:@"childrenCount"];
	
	// Check if [value] is an ARRAY
	if ([snapshot.value isKindOfClass:[NSArray class]])
	{
		[payload setObject:snapshot.value forKey:@"value"];
		[payload setObject:[NSNumber numberWithInteger:0] forKey:@"childrenCount"];
	}
	
	// Use [children] to set [value] w/Priority
	else if (snapshot.childrenCount)
	{
		// Initialize the [children]
		NSMutableDictionary *children = [NSMutableDictionary dictionary];
		
		for (FDataSnapshot *child in snapshot.children)
		{
			[children setObject:[self FDataSnapshotSpider:child] forKey:child.name];
		}
		
		[payload setObject:children forKey:@"value"];
	}
	
	// No [children]
	else
	{[payload setObject:snapshot.value forKey:@"value"];}
	
	return payload;
}

@end
